version: "3.7"
services:
    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./public:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql
        container_name: mysql-db
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    # PhpMyadmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sitezappts-phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 8888:80
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./public:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
